a = int(input("ENTER THE VALUE OF a : "))
b = int(input("ENTER THE VALUE OF b : "))
c = a + b
d = a - b
e = a * b
f = a // b
print(a,"+",b,"=",c)
print(a,"-",b,"=",d) 
print(a,"*",b,"=",e) 
print(a,"/",b,"=",f)
