# REMOVING STRING FROM ANOTHER STRING #
def removeString(STRING1,STRING2):
    STRING3 =  STRING1.replace(STRING2,"")
    print(STRING3)

STRING1 = input("ENTER THE STRING : ")
STRING2 = input("ENTER THE STRING TO BE REMOVED : ")
removeString(STRING1,STRING2)